[{
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "web",
    "site": "https://kriptor.mobileinnova.com"
  }
},{
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "android_app",
    "package_name": "com.mobileinnova.kriptor",
    "sha256_cert_fingerprints": ["68:1A:C0:97:9F:6F:06:F6:8A:51:10:69:DA:41:47:76:DD:7F:82:A1:F4:02:20:55:60:ED:BD:F6:A6:8B:65:A2","93:15:5D:31:D6:91:25:0A:76:97:04:B4:4B:32:0A:06:CE:5D:61:A1:20:64:B1:43:53:BE:E2:7F:B4:EB:5F:BE"]
  }
}]