[{
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "web",
    "site": "https://kriptor.mobileinnova.com"
  }
},{
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "android_app",
    "package_name": "com.mobileinnova.kriptor",
    "sha256_cert_fingerprints": ["68:1A:C0:97:9F:6F:06:F6:8A:51:10:69:DA:41:47:76:DD:7F:82:A1:F4:02:20:55:60:ED:BD:F6:A6:8B:65:A2"]
  }
}]