{
  "applinks": {
      "details": [
           {
             "appIDs": [ "com.mobileinnova.kriptor" ],
             "components": [
               {
                  "#": "no_universal_links",
                  "exclude": true,
                  "comment": "Matches any URL whose fragment equals no_universal_links and instructs the system not to open it as a universal link"
               },
               {
                  "/": "/recoverPassword/*",
                  "comment": "Matches any URL whose path starts with /recoverPassword/"
               }
             ]
           }
       ]
   }
}