<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script type="text/javascript">
            function whenLoad() {
                var searchParams = window.location.search;
                window.location.href = "kriptor://recoverPassword/" + searchParams;
            }
        </script>
    </head>
<body onLoad="whenLoad()">
<a href="#" oncick="whenLoad()">Tap here to continue...</a>
</body>
</html>